In [148]:
import pandas as pd
import MySQLdb
from sqlalchemy import create_engine

### DB Connection

In [149]:
# DB Connection
myvars = {}
with open("../risaac-mysql-password") as myfile:
    for line in myfile:
        name, var = line.partition(":")[::2]
        myvars[name.strip()] = var.strip()

In [150]:
myvars['DB databasename'] = 'I501saptpurkFall22grp_06_db'

In [151]:
myvars

{'DB username': 'risaac',
 'DB databasename': 'I501saptpurkFall22grp_06_db',
 'DB password': 'denounced eliding lushness'}

In [152]:
my_conn = create_engine(f"mysql+mysqldb://{myvars['DB username']}:{myvars['DB password']}@localhost/{myvars['DB databasename']}") #fill details

### P_DEMO

In [153]:
df_p_demo = pd.read_csv('P_DEMO.csv')

In [154]:
df_p_demo.shape

(15560, 29)

In [155]:
# check for unique values in each column in demographics data
for col in df_p_demo.columns:
    print("============================")
    print("============================")
    print("        ", col, "       ")
    print(df_p_demo[col].unique()[:15])

         SEQN        
[109263. 109264. 109265. 109266. 109267. 109268. 109269. 109270. 109271.
 109272. 109273. 109274. 109275. 109276. 109277.]
         SDDSRVYR        
[66.]
         RIDSTATR        
[2. 1.]
         RIAGENDR        
[1. 2.]
         RIDAGEYR        
[2.00000000e+00 1.30000000e+01 2.90000000e+01 2.10000000e+01
 1.80000000e+01 1.10000000e+01 4.90000000e+01 5.39760535e-79
 3.60000000e+01 6.80000000e+01 6.00000000e+00 1.20000000e+01
 1.70000000e+01 7.60000000e+01 5.20000000e+01]
         RIDAGEMN        
[nan  3.  2.  1. 10. 23.  8.  9.  5. 16. 21. 12. 11. 22.  7.]
         RIDRETH1        
[5. 1. 3. 2. 4.]
         RIDRETH3        
[6. 1. 3. 2. 4. 7.]
         RIDEXMON        
[ 2. nan  1.]
         DMDBORN4        
[ 1.  2. 77. 99.]
         DMDYRUSZ        
[nan  2.  3.  4.  1. 99. 77.]
         DMDEDUC2        
[nan  5.  4.  2.  3.  1.  9.  7.]
         DMDMARTZ        
[nan  3.  1.  2. 77. 99.]
         RIDEXPRG        
[nan  2.  3.  1.]
         SIALANG        
[

In [156]:
cols = ['SEQN'
         ,'SDDSRVYR'
         ,'RIDSTATR'
         ,'RIAGENDR'
#          ,'RIDAGEYR' -- inconsistent data points ex: 5.39760535e-79
#          ,'RIDAGEMN' -- inconsistent data points ex: 5.39760535e-79
         ,'RIDRETH1'
         ,'RIDRETH3'
         ,'RIDEXMON'
         ,'DMDBORN4'
         ,'DMDYRUSZ'
         ,'DMDEDUC2'
         ,'DMDMARTZ'
         ,'RIDEXPRG'
         ,'SIALANG'
         ,'SIAPROXY'
         ,'SIAINTRP'
         ,'FIALANG'
         ,'FIAPROXY'
         ,'FIAINTRP'
         ,'MIALANG'
         ,'MIAPROXY'
         ,'MIAINTRP'
         ,'AIALANGA'
         ,'SDMVPSU'
         ,'SDMVSTRA']

df_p_demo[cols] = df_p_demo[cols].astype("Int32")

In [157]:
cols = ['RIDAGEYR'
        ,'RIDAGEMN'
       ]

df_p_demo[cols] = df_p_demo[cols].round().astype("Int32")

In [158]:
cols = ['WTINTPRP'
         ,'WTMECPRP'
         ,'INDFMPIR']

df_p_demo[cols] = df_p_demo[cols].round(2).astype(float)

In [159]:
df_p_demo = df_p_demo.replace({np.nan:None})

In [160]:
name = "P_DEMO"
df_p_demo.to_sql(name, con = my_conn, if_exists = 'replace', index = False)

15560

### P_HIQ

In [161]:
df_p_hiq = pd.read_csv('P_HIQ.csv')

In [162]:
df_p_hiq.shape

(15560, 14)

In [163]:
# check for unique values in each column in demographics data
for col in df_p_hiq.columns:
    print("============================")
    print("============================")
    print("        ", col, "       ")
    print(df_p_hiq[col].unique())

         SEQN        
[109263. 109264. 109265. ... 124820. 124821. 124822.]
         HIQ011        
[1. 2. 9. 7.]
         HIQ032A        
[ 1. nan 99. 77.]
         HIQ032B        
[nan  2.]
         HIQ032C        
[nan  3.]
         HIQ032D        
[nan  4.]
         HIQ032E        
[nan  5.]
         HIQ032H        
[nan  8.]
         HIQ032I        
[nan  9.]
         HIQ032J        
[nan 10.]
         HIQ260        
[nan  1.  2.  7.  9.]
         HIQ105        
[nan  2.  1.]
         HIQ270        
[ 1.  2. nan  9.  7.]
         HIQ210        
[ 2.  1. nan  9.  7.]


In [164]:
cols = ['SEQN'
       ,'HIQ011'
       ,'HIQ032A'
       ,'HIQ032B'
       ,'HIQ032C'
       ,'HIQ032D'
       ,'HIQ032E'
       ,'HIQ032H'
       ,'HIQ032I'
       ,'HIQ032J'
       ,'HIQ260'
       ,'HIQ105'
       ,'HIQ270'
       ,'HIQ210']

df_p_hiq[cols] = df_p_hiq[cols].astype("Int32")

In [165]:
df_p_hiq = df_p_hiq.replace({np.nan:None})

In [166]:
name = "P_HIQ"
df_p_hiq.to_sql(name, con = my_conn, if_exists = 'replace', index_label = "hiq_key")

15560

### P_HUQ

In [167]:
df_p_huq = pd.read_csv('P_HUQ.csv')

In [168]:
df_p_huq.shape

(15560, 7)

In [169]:
# check for unique values in each column in demographics data
for col in df_p_huq.columns:
    print("============================")
    print("============================")
    print("        ", col, "       ")
    print(df_p_huq[col].unique())

         SEQN        
[109263. 109264. 109265. ... 124820. 124821. 124822.]
         HUQ010        
[1. 2. 3. 4. 5. 7. 9.]
         HUQ030        
[1. 2. 3. 7. 9.]
         HUQ051        
[1.00000000e+00 5.39760535e-79 2.00000000e+00 4.00000000e+00
 3.00000000e+00 8.00000000e+00 5.00000000e+00 6.00000000e+00
 7.00000000e+00 9.90000000e+01]
         HUD062        
[           nan 2.00000000e+00 1.00000000e+00 3.00000000e+00
 5.39760535e-79 9.90000000e+01 4.00000000e+00]
         HUQ071        
[2. 1. 9.]
         HUQ090        
[nan  1.  2.  9.  7.]


In [170]:
cols = ['SEQN'
        ,'HUQ010'
        ,'HUQ030'
        ,'HUQ071'
        ,'HUQ090'
       ]

df_p_huq[cols] = df_p_huq[cols].astype("Int32")

In [171]:
cols = ['HUQ051'
       ,'HUD062']

df_p_huq[cols] = df_p_huq[cols].round().astype("Int32")

In [172]:
df_p_huq = df_p_huq.replace({np.nan:None})

In [173]:
name = "P_HUQ"
df_p_huq.to_sql(name, con = my_conn, if_exists = 'replace', index_label = "huq_key")

15560