In [112]:
import pandas as pd
import MySQLdb
import numpy as np
from sqlalchemy import create_engine
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 500)

In [113]:
# DB Connection
myvars = {}
with open("../risaac-mysql-password") as myfile:
    for line in myfile:
        name, var = line.partition(":")[::2]
        myvars[name.strip()] = var.strip()

In [114]:
myvars['DB databasename'] = 'I501saptpurkFall22grp_06_db'

In [115]:
conn = MySQLdb.connect(host="localhost", user=myvars['DB username'], passwd=myvars['DB password'], db=myvars['DB databasename'])
cursor = conn.cursor()

In [116]:
df_p_demo = pd.read_sql('select * from P_DEMO', conn)

/usr/local/lib/python3.10/dist-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(


In [117]:
df_p_demo

SEQN  SDDSRVYR  RIDSTATR  RIAGENDR  RIDAGEYR  RIDAGEMN  RIDRETH1  \
0      109263        66         2         1         2       NaN         5   
1      109264        66         2         2        13       NaN         1   
2      109265        66         2         1         2       NaN         3   
3      109266        66         2         2        29       NaN         5   
4      109267        66         1         2        21       NaN         2   
...       ...       ...       ...       ...       ...       ...       ...   
15555  124818        66         2         1        40       NaN         4   
15556  124819        66         2         1         2       NaN         4   
15557  124820        66         2         2         7       NaN         3   
15558  124821        66         2         1        63       NaN         4   
15559  124822        66         2         1        74       NaN         2   

       RIDRETH3  RIDEXMON  DMDBORN4  DMDYRUSZ  DMDEDUC2  DMDMARTZ  RIDEXPRG  \
0             6       2.0         1       NaN       NaN       NaN       NaN   
1             1       2.0         1       NaN       NaN       NaN       NaN   
2             3       2.0         1       NaN       NaN       NaN       NaN   
3             6       2.0         2       2.0       5.0       3.0       2.0   
4             2       NaN         2       3.0       4.0       3.0       3.0   
...         ...       ...       ...       ...       ...       ...       ...   
15555         4       1.0         1       NaN       5.0       1.0       NaN   
15556         4       2.0         1       NaN       NaN       NaN       NaN   
15557         3       2.0         1       NaN       NaN       NaN       NaN   
15558         4       1.0         1       NaN       2.0       2.0       NaN   
15559         2       2.0         2       4.0       3.0       1.0       NaN   

       SIALANG  SIAPROXY  SIAINTRP  FIALANG  FIAPROXY  FIAINTRP  MIALANG  \
0            1         1         2      1.0       2.0       2.0      NaN   
1            1         1         2      1.0       2.0       2.0      1.0   
2            1         1         2      1.0       2.0       2.0      NaN   
3            1         2         2      1.0       2.0       2.0      1.0   
4            1         2         2      1.0       2.0       2.0      NaN   
...        ...       ...       ...      ...       ...       ...      ...   
15555        1         2         2      1.0       2.0       2.0      1.0   
15556        1         1         2      1.0       2.0       2.0      NaN   
15557        1         1         2      1.0       2.0       2.0      NaN   
15558        1         2         2      1.0       2.0       2.0      1.0   
15559        2         2         2      NaN       NaN       NaN      2.0   

       MIAPROXY  MIAINTRP  AIALANGA  WTINTPRP  WTMECPRP  SDMVPSU  SDMVSTRA  \
0           NaN       NaN       NaN   7891.76   8951.82        3       156   
1           2.0       2.0       1.0  11689.75  12271.16        1       155   
2           NaN       NaN       NaN  16273.83  16658.76        1       157   
3           2.0       2.0       1.0   7825.65   8154.97        2       168   
4           NaN       NaN       NaN  26379.99      0.00        1       156   
...         ...       ...       ...       ...       ...      ...       ...   
15555       2.0       2.0       1.0  21586.60  21666.89        1       166   
15556       NaN       NaN       NaN   1664.92   1838.17        2       171   
15557       NaN       NaN       NaN  14819.78  16497.81        1       157   
15558       2.0       2.0       1.0   4666.82   4853.43        1       158   
15559       2.0       2.0       NaN  14024.48  15195.80        1       149   

       INDFMPIR  
0          4.66  
1          0.83  
2          3.06  
3          5.00  
4          5.00  
...         ...  
15555      3.82  
15556      0.07  
15557      1.22  
15558      3.71  
15559       NaN  

[15560 rows x 29 columns]

In [118]:
df_p_demo.isna().sum()

SEQN            0
SDDSRVYR        0
RIDSTATR        0
RIAGENDR        0
RIDAGEYR        0
RIDAGEMN    14573
RIDRETH1        0
RIDRETH3        0
RIDEXMON     1260
DMDBORN4        0
DMDYRUSZ    12532
DMDEDUC2     6328
DMDMARTZ     6328
RIDEXPRG    13686
SIALANG         0
SIAPROXY        0
SIAINTRP        0
FIALANG      1079
FIAPROXY     1079
FIAINTRP     1079
MIALANG      4560
MIAPROXY     4560
MIAINTRP     4560
AIALANGA     7336
WTINTPRP        0
WTMECPRP        0
SDMVPSU         0
SDMVSTRA        0
INDFMPIR     2201
dtype: int64

<b> RIDAGEMN

RIDAGEMN: Age in months, at the time of the screening interview, is provided for participants who were less than 25 months of age at the time of examination (RIDEXAGM < 25). If the exact date of birth was not provided by the respondent, the age in months was calculated based on the imputed age in years at the time of the screening interview.

RIDAGEYR was calculated based on the participant’s date of birth. In rare cases, if the actual date of birth was missing but the participant’s age in years was provided, the reported age was used.
RIDAGEMN: Age in months, at the time of the screening interview, is provided for participants who were less than 25 months of age at the time of examination (RIDEXAGM < 25). If the exact date of birth was not provided by the respondent, the age in months was calculated based on the imputed age in years at the time of the screening interview.

In [119]:
# RIDAGEMN -> Age in Months for people below the age of 2 years
# We can impute from column RIDAGEYR -> Age in Years

# check unique values
df_p_demo["RIDAGEMN"].unique()

array([nan,  3.,  2.,  1., 10., 23.,  8.,  9.,  5., 16., 21., 12., 11.,
       22.,  7., 17.,  4., 14., 15.,  6., 18., 19.,  0., 13., 20., 24.])

In [120]:
# validate age in months columns to have age in years less than 2 years as per column definition
df_p_demo[["RIDAGEMN", "RIDAGEYR"]].dropna(subset = ["RIDAGEMN"])["RIDAGEYR"].unique()

array([0, 1, 2])

In [121]:
# replace null values with age in years multiplied by 12
df_p_demo.loc[df_p_demo["RIDAGEMN"].isna(), "RIDAGEMN"] = df_p_demo.loc[df_p_demo["RIDAGEMN"].isna(), "RIDAGEYR"] * 12

In [122]:
df_p_demo[['RIDAGEMN', 'RIDAGEYR']]

RIDAGEMN  RIDAGEYR
0          24.0         2
1         156.0        13
2          24.0         2
3         348.0        29
4         252.0        21
...         ...       ...
15555     480.0        40
15556      24.0         2
15557      84.0         7
15558     756.0        63
15559     888.0        74

[15560 rows x 2 columns]

In [123]:
# validate all values imputed for RIDAGEMN
df_p_demo['RIDAGEMN'].isna().sum()

0

RIDEXMON


RIDEXMON: This variable indicates the six-month time period when the examination was performed. A value of “1” indicates November 1st through April 30th; a value of “2” indicates May 1st through October 31st.

In [124]:
df_p_demo[df_p_demo["RIDEXMON"].isna()] # the variable is not important since it talks about when the survey was done

SEQN  SDDSRVYR  RIDSTATR  RIAGENDR  RIDAGEYR  RIDAGEMN  RIDRETH1  \
4      109267        66         1         2        21     252.0         2   
5      109268        66         1         2        18     216.0         3   
20     109283        66         1         1        52     624.0         5   
36     109299        66         1         2         4      48.0         5   
48     109311        66         1         2        36     432.0         2   
...       ...       ...       ...       ...       ...       ...       ...   
15475  124738        66         1         2        47     564.0         3   
15488  124751        66         1         1        37     444.0         2   
15497  124760        66         1         2        27     324.0         3   
15532  124795        66         1         2         5      60.0         2   
15545  124808        66         1         2        26     312.0         3   

       RIDRETH3  RIDEXMON  DMDBORN4  DMDYRUSZ  DMDEDUC2  DMDMARTZ  RIDEXPRG  \
4             2       NaN         2       3.0       4.0       3.0       3.0   
5             3       NaN         1       NaN       NaN       NaN       NaN   
20            7       NaN         1       NaN       3.0       2.0       NaN   
36            7       NaN         1       NaN       NaN       NaN       NaN   
48            2       NaN         1       NaN       4.0       3.0       3.0   
...         ...       ...       ...       ...       ...       ...       ...   
15475         3       NaN         1       NaN       4.0       3.0       NaN   
15488         2       NaN         1       NaN       3.0       1.0       NaN   
15497         3       NaN         1       NaN       3.0       1.0       3.0   
15532         2       NaN         1       NaN       NaN       NaN       NaN   
15545         3       NaN         1       NaN       3.0       1.0       3.0   

       SIALANG  SIAPROXY  SIAINTRP  FIALANG  FIAPROXY  FIAINTRP  MIALANG  \
4            1         2         2      1.0       2.0       2.0      NaN   
5            1         2         2      1.0       2.0       2.0      NaN   
20           1         2         2      1.0       2.0       2.0      NaN   
36           1         1         2      1.0       2.0       2.0      NaN   
48           1         2         2      1.0       2.0       2.0      NaN   
...        ...       ...       ...      ...       ...       ...      ...   
15475        1         2         2      1.0       2.0       2.0      NaN   
15488        2         2         1      2.0       2.0       1.0      NaN   
15497        1         2         2      1.0       2.0       2.0      NaN   
15532        1         1         2      1.0       2.0       2.0      NaN   
15545        1         2         2      NaN       NaN       NaN      NaN   

       MIAPROXY  MIAINTRP  AIALANGA   WTINTPRP  WTMECPRP  SDMVPSU  SDMVSTRA  \
4           NaN       NaN       NaN   26379.99       0.0        1       156   
5           NaN       NaN       NaN   19639.22       0.0        1       155   
20          NaN       NaN       NaN   42539.68       0.0        2       149   
36          NaN       NaN       NaN    5555.40       0.0        2       155   
48          NaN       NaN       NaN   28442.98       0.0        1       166   
...         ...       ...       ...        ...       ...      ...       ...   
15475       NaN       NaN       NaN   37944.07       0.0        2       149   
15488       NaN       NaN       NaN   47634.52       0.0        2       161   
15497       NaN       NaN       NaN   25006.83       0.0        1       167   
15532       NaN       NaN       NaN   13183.45       0.0        2       166   
15545       NaN       NaN       NaN  120856.82       0.0        2       149   

       INDFMPIR  
4          5.00  
5          1.66  
20         0.96  
36         5.00  
48         3.39  
...         ...  
15475      0.80  
15488      1.79  
15497      1.41  
15532      5.00  
15545       NaN  

[1260 rows x 29 columns]

In [125]:
df_p_demo = df_p_demo.drop("RIDEXMON", axis = 1)

DMDBORN4

DMDBORN4: Due to the concerns of disclosure risk, starting in 2011, country of birth was recoded into two categories: 1) Born in 50 U.S. states or Washington, DC; and 2) Born in other countries, including U.S. territories.

In [126]:
df_p_demo["DMDBORN4"].unique()

array([ 1,  2, 77, 99])

In [127]:
# Replacing the below values with nulls
# values 77 => Refused, 99 => Don't Know
df_p_demo["DMDBORN4"] = df_p_demo["DMDBORN4"].replace([77,99], None)

DMDYRUSZ

DMDYRUSZ: This variable is the number of years the participant has lived in the United States. Participants who were born outside the U.S. were asked the month and year when they came to the U.S. to live (DMQ.160). The responses to the question were used to calculated the length of these participants lived in the US and then recoded into 4 categories: 1 = Less than 5 year, 2 = 5 year or more, but less than 15 years, 3 = 15 year or more, but less than 30 years, and 4 = 30 year or more. For participants who did not report the month of their arrival, a month value of 7 (July) was imputed in the calculation of the residence length.

In [128]:
df_p_demo["DMDYRUSZ"].unique()

array([nan,  2.,  3.,  4.,  1., 99., 77.])

In [129]:
# Based on the feature description, we assume the missing values are from respondents who are born in the U.S
# as the description says "Participants who were born outside the U.S. were asked the month and year when they came to the U.S. to live "

# we impute by providing a separate class to people born in the US

df_p_demo.loc[df_p_demo['DMDYRUSZ'].isna(), "DMDYRUSZ"] = 5

In [130]:
df_p_demo["DMDYRUSZ"] = df_p_demo["DMDYRUSZ"].replace([77,99], None)

In [131]:
df_p_demo["DMDYRUSZ"].isna().sum()

134

In [132]:
df_p_demo["DMDYRUSZ"].value_counts()

5.0    12532
3.0      935
4.0      864
2.0      594
1.0      501
Name: DMDYRUSZ, dtype: int64

DMDEDUC2

DMDEDUC2: This variable is the highest grade or level of education completed by adults 20 years and older. The response categories are: less than 9th grade education, 9-11th grade education (includes 12th grade and no diploma), High school graduate/GED, some college or associates (AA) degree, and college graduate or higher.

In [133]:
# ages for which highest grade is not available
np.sort(df_p_demo[df_p_demo["DMDEDUC2"].isna()]['RIDAGEYR'].unique())

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [134]:
# check if all missing values are for people under age 20
np.sort(df_p_demo[df_p_demo['DMDEDUC2'].isna()][['RIDAGEYR', 'DMDEDUC2']]['RIDAGEYR'].unique())

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [135]:
# create a new class 6 => represents age less than 20
df_p_demo.loc[(df_p_demo["DMDEDUC2"].isna() & (df_p_demo["RIDAGEYR"] < 20)), "DMDEDUC2"] = 6

In [136]:
# check if all missing values are imputed
df_p_demo["DMDEDUC2"].isna().sum()

0

In [137]:
# make 7,9 classes as None
# 7 => Refused
# 8 => Dont Know
df_p_demo.loc[df_p_demo["DMDEDUC2"].isin([7,9]), "DMDEDUC2"] = np.nan

In [138]:
df_p_demo["DMDEDUC2"].value_counts()

6.0    6328
4.0    2975
5.0    2257
3.0    2225
2.0    1041
1.0     719
Name: DMDEDUC2, dtype: int64

In [139]:
# check number of missing values
df_p_demo["DMDEDUC2"].isna().sum()

15

DMDMARTZ

DMDMARTZ: The marital status question was asked of persons 14 years of age and older. Due to disclosure risks, marital status is only released for persons 20 years of age and older, and recoded from the original 6 categories to 3 categories (1 = Married/Living with partner; 2 = Widowed/Divorced/Separated; 3 = Never married).

In [140]:
# check missing values
df_p_demo['DMDMARTZ'].isna().sum()

6328

In [141]:
# Missing values follow same pattern as the previous feature - DMDEDUC2

# check if all missing values are for people under age 20
np.sort(df_p_demo[df_p_demo['DMDMARTZ'].isna()][['RIDAGEYR', 'DMDMARTZ']]['RIDAGEYR'].unique())

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [142]:
# check unique values
df_p_demo['DMDMARTZ'].value_counts()

1.0     5279
2.0     2148
3.0     1795
77.0       8
99.0       2
Name: DMDMARTZ, dtype: int64

In [143]:
# create a new class 4 => represents age less than 20
df_p_demo.loc[(df_p_demo["DMDMARTZ"].isna() & (df_p_demo["RIDAGEYR"] < 20)), "DMDMARTZ"] = 4

In [144]:
# make 77,99 classes as None
# 77 => Refused
# 99 => Dont Know
df_p_demo.loc[df_p_demo["DMDMARTZ"].isin([77,99]), "DMDMARTZ"] = np.nan

In [145]:
# check number of missing values
df_p_demo["DMDMARTZ"].isna().sum()

10

RIDEXPRG

RIDEXPRG: Pregnancy status at the time of the health examination was ascertained for females 8–59 years of age. Due to disclosure risks pregnancy status is only released for women 20-44 years of age. The information used to code RIDEXPRG values included self-reported pregnancy status and urine pregnancy test results. Persons who reported they were pregnant at the time of exam were assumed to be pregnant (RIDEXPRG=1). Those who reported they were not pregnant or did not know their pregnancy status were further classified based on the results of the urine pregnancy test. If the respondent reported “no” or “don’t know” and the urine test result was positive, the respondent was coded as pregnant (RIDEXPRG=1). If the respondent reported “no” and the urine test was negative, the respondent was coded not pregnant (RIDEXPRG=2). If the respondent reported did not know her pregnancy status and the urine test was negative, the respondent was coded "could not be determined” (RIDEXPRG=3). Persons who were interviewed, but not examined also have an RIDEXPRG value = 3 (could not be determined).

In [146]:
# check unique values
df_p_demo['RIDEXPRG'].unique()

array([nan,  2.,  3.,  1.])

In [147]:
# we know that information for people of ages 20-44 are only given, lets verify

# check ages of all respondents where RIDEXPRG is missing
np.sort(df_p_demo[df_p_demo['RIDEXPRG'].isna()]['RIDAGEYR'].unique())

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

In [148]:
# check ages of all respondents where RIDEXPRG is available
np.sort(df_p_demo[~df_p_demo['RIDEXPRG'].isna()]['RIDAGEYR'].unique())

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44])

In [149]:
# it is less likely that people below 20 yrs of age and above 44 yrs of age to be pregnant,

# check if people between ages 20 and 40 are missing values because they are males
df_p_demo[df_p_demo['RIDEXPRG'].isna()][['RIDAGEYR', 'RIAGENDR', 'SEQN']].sort_values("RIDAGEYR").groupby(["RIDAGEYR", "RIAGENDR"])['SEQN'].count()

# we see all the nulls between ages 20 to 40 are of gender Male, we can say they are not pregnant

RIDAGEYR  RIAGENDR
0         1           292
          2           282
1         1           219
          2           187
2         1           212
                     ... 
78        2            37
79        1            38
          2            31
80        1           332
          2           350
Name: SEQN, Length: 137, dtype: int64

In [150]:
# we can impute a separate class value 4 representing no testing for males and people with age < 20 and age > 44 (all nulls)
df_p_demo.loc[df_p_demo['RIDEXPRG'].isna(), "RIDEXPRG"] = 4

In [151]:
df_p_demo['RIDEXPRG'].value_counts()

4.0    13686
2.0     1604
3.0      183
1.0       87
Name: RIDEXPRG, dtype: int64

In [152]:
# check nulls after imputation
df_p_demo[df_p_demo['RIDEXPRG'].isna()]['RIDAGEYR'].value_counts().sort_index()

Series([], Name: RIDAGEYR, dtype: int64)

The following features,
- FIALANG
- FIAPROXY
- FIAINTRP
- MIALANG
- MIAPROXY
- MIAINTRP
- AIALANGA

are representative of language and interpreter used during the respondent interview. These features can be represented by SIALANG which also talks about respondent language of use
Imputing the rest of the variables can be done but will add bias to the data. Hence we decide to drop them.

In [153]:
df_p_demo = df_p_demo.drop(['FIALANG','FIAPROXY','FIAINTRP', 'MIALANG', 'MIAPROXY', 'MIAINTRP', 'AIALANGA'], axis = 1)

INDFMPIR: This variable is the ratio of family income to poverty. The Department of Health and Human Services (HHS) poverty guidelines were used as the poverty measure to calculate this ratio. These guidelines are issued each year, in the Federal Register, for determining financial eligibility for certain federal programs, such as Head Start, Supplemental Nutrition Assistance Program (SNAP), Special Supplemental Nutrition Program for Women, Infants, and Children (WIC), and the National School Lunch Program. The poverty guidelines vary by family size and geographic location (with different guidelines for the 48 contiguous states and the District of Columbia; Alaska; and Hawaii).

INDFMPIR was calculated by dividing total annual family (or individual) income by the poverty guidelines specific to the survey year. 

During the household interview, the respondent was asked to report total income for the entire family in the last calendar year in dollars. A family is defined as a group of two people or more related by birth, marriage, or adoption and residing together. Annual individual income was asked for households with one person or households comprised of unrelated individuals. 

If the respondent was not willing or able to provide an exact dollar figure, the interviewer asked an additional question to determine whether the income was < $20,000 or ≥ $20,000. Based on the respondent’s answer to this question, he/she was asked to select a category of income from a list on a hand card. For respondents who selected a category of income, their family incomes were set as the midpoints of the selected ranges. INDFMPIR was not computed if the respondent only reported income as < $20,000 or ≥ $20,000 but no additional details provided. INDFMPIR values at or above 5.00 were coded as 5.00 or more because of disclosure concerns. The values were not computed if the income data was missing.

In [154]:
# number of nans
df_p_demo['INDFMPIR'].isna().sum()

2201

In [155]:
# describing values where data is missing for INDFMPIR
df_p_demo[df_p_demo['INDFMPIR'].isna()].describe()

# we can impute INDFMPIR with the HHS guidelines values but we are not aware of Persons in family/household of the respondent
# which is required to the find the right poverty guideline

SEQN  SDDSRVYR     RIDSTATR     RIAGENDR     RIDAGEYR  \
count    2201.000000    2201.0  2201.000000  2201.000000  2201.000000   
mean   116890.857792      66.0     1.839164     1.489777    35.896411   
std      4465.607808       0.0     0.367463     0.500009    25.471824   
min    109271.000000      66.0     1.000000     1.000000     0.000000   
25%    112954.000000      66.0     2.000000     1.000000    11.000000   
50%    116707.000000      66.0     2.000000     1.000000    34.000000   
75%    120683.000000      66.0     2.000000     2.000000    59.000000   
max    124822.000000      66.0     2.000000     2.000000    80.000000   

          RIDAGEMN     RIDRETH1     RIDRETH3     DMDEDUC2     DMDMARTZ  \
count  2201.000000  2201.000000  2201.000000  2190.000000  2194.000000   
mean    431.029986     3.228078     3.465243     4.277169     2.528259   
std     305.285644     1.322791     1.695126     1.666146     1.288121   
min       0.000000     1.000000     1.000000     1.000000     1.000000   
25%     132.000000     2.000000     2.000000     3.000000     1.000000   
50%     408.000000     3.000000     3.000000     4.000000     3.000000   
75%     708.000000     4.000000     4.000000     6.000000     4.000000   
max     960.000000     5.000000     7.000000     6.000000     4.000000   

          RIDEXPRG      SIALANG     SIAPROXY     SIAINTRP       WTINTPRP  \
count  2201.000000  2201.000000  2201.000000  2201.000000    2201.000000   
mean      3.777374     1.183553     1.686506     1.969105   18007.105566   
std       0.625559     0.387207     0.464019     0.173073   22014.011648   
min       1.000000     1.000000     1.000000     1.000000    1513.710000   
25%       4.000000     1.000000     1.000000     2.000000    6959.630000   
50%       4.000000     1.000000     2.000000     2.000000   11746.520000   
75%       4.000000     1.000000     2.000000     2.000000   20362.940000   
max       4.000000     2.000000     2.000000     2.000000  282883.650000   

            WTMECPRP      SDMVPSU     SDMVSTRA  INDFMPIR  
count    2201.000000  2201.000000  2201.000000       0.0  
mean    16186.342244     1.524307   160.096320       NaN  
std     22633.341812     0.535533     7.293695       NaN  
min         0.000000     1.000000   149.000000       NaN  
25%      4911.200000     1.000000   153.000000       NaN  
50%     10547.490000     2.000000   159.000000       NaN  
75%     19486.680000     2.000000   167.000000       NaN  
max    308014.510000     3.000000   172.000000       NaN

In [156]:
# before imputing we will remove rows with nans for all columns except INDFMPIR
# this is done to support imputing for INDFMPIR through KNNs as KNNs dont accept nulls
# and we have less than 150 rows where we still have nans
# the nans are representative of survey answers that fall under "Refused", "Dont Know"

df_p_demo.isna().sum()

SEQN           0
SDDSRVYR       0
RIDSTATR       0
RIAGENDR       0
RIDAGEYR       0
RIDAGEMN       0
RIDRETH1       0
RIDRETH3       0
DMDBORN4       7
DMDYRUSZ     134
DMDEDUC2      15
DMDMARTZ      10
RIDEXPRG       0
SIALANG        0
SIAPROXY       0
SIAINTRP       0
WTINTPRP       0
WTMECPRP       0
SDMVPSU        0
SDMVSTRA       0
INDFMPIR    2201
dtype: int64

In [157]:
df_p_demo = df_p_demo[~df_p_demo[["DMDBORN4", "DMDYRUSZ", "DMDEDUC2", "DMDMARTZ"]].isna().any(axis = 1)]

In [158]:
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler

In [159]:
# we can impute the data using a KNN approach and add it as a separate column "INDFMPIR_imputed"
# we do this so as to test model performance with and without imputed values

imputer = KNNImputer(n_neighbors = 1)

In [160]:
df_p_demo.columns

Index(['SEQN', 'SDDSRVYR', 'RIDSTATR', 'RIAGENDR', 'RIDAGEYR', 'RIDAGEMN',
       'RIDRETH1', 'RIDRETH3', 'DMDBORN4', 'DMDYRUSZ', 'DMDEDUC2', 'DMDMARTZ',
       'RIDEXPRG', 'SIALANG', 'SIAPROXY', 'SIAINTRP', 'WTINTPRP', 'WTMECPRP',
       'SDMVPSU', 'SDMVSTRA', 'INDFMPIR'],
      dtype='object')

In [161]:
# we will use only logical columns to impute the data
cols = ['RIAGENDR', 'RIDAGEYR', 'RIDAGEMN',
       'RIDRETH1', 'RIDRETH3', 'DMDBORN4', 'DMDYRUSZ', 'DMDEDUC2', 'DMDMARTZ',
       'RIDEXPRG', 'SIALANG', 'INDFMPIR']

df_p_demo[cols]

RIAGENDR  RIDAGEYR  RIDAGEMN  RIDRETH1  RIDRETH3 DMDBORN4 DMDYRUSZ  \
0             1         2      24.0         5         6        1      5.0   
1             2        13     156.0         1         1        1      5.0   
2             1         2      24.0         3         3        1      5.0   
3             2        29     348.0         5         6        2      2.0   
4             2        21     252.0         2         2        2      3.0   
...         ...       ...       ...       ...       ...      ...      ...   
15555         1        40     480.0         4         4        1      5.0   
15556         1         2      24.0         4         4        1      5.0   
15557         2         7      84.0         3         3        1      5.0   
15558         1        63     756.0         4         4        1      5.0   
15559         1        74     888.0         2         2        2      4.0   

       DMDEDUC2  DMDMARTZ  RIDEXPRG  SIALANG  INDFMPIR  
0           6.0       4.0       4.0        1      4.66  
1           6.0       4.0       4.0        1      0.83  
2           6.0       4.0       4.0        1      3.06  
3           5.0       3.0       2.0        1      5.00  
4           4.0       3.0       3.0        1      5.00  
...         ...       ...       ...      ...       ...  
15555       5.0       1.0       4.0        1      3.82  
15556       6.0       4.0       4.0        1      0.07  
15557       6.0       4.0       4.0        1      1.22  
15558       2.0       2.0       4.0        1      3.71  
15559       3.0       1.0       4.0        2       NaN  

[15400 rows x 12 columns]

In [162]:
# relabel gender column from 1, 2 to 0,1
df_p_demo.loc[df_p_demo["RIAGENDR"] == 1, "RIAGENDR"] = 0
df_p_demo.loc[df_p_demo["RIAGENDR"] == 2, "RIAGENDR"] = 1

# Assign SEQN as index to use later
df_p_demo_subset = df_p_demo.set_index("SEQN")[cols]

# identify columns to encode
df_p_demo_subset_dummified = pd.get_dummies(df_p_demo_subset, columns = ["RIDRETH1", "RIDRETH3", "DMDBORN4", "DMDEDUC2", "DMDMARTZ",
                                           "RIDEXPRG", "SIALANG"], drop_first=True)

cols_dummified = df_p_demo_subset_dummified.columns

/usr/local/lib/python3.10/dist-packages/pandas/core/algorithms.py:798: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  uniques = Index(uniques)


In [163]:
df_p_demo_subset_dummified

RIAGENDR  RIDAGEYR  RIDAGEMN DMDYRUSZ  INDFMPIR  RIDRETH1_2  \
SEQN                                                                  
109263         0         2      24.0      5.0      4.66           0   
109264         1        13     156.0      5.0      0.83           0   
109265         0         2      24.0      5.0      3.06           0   
109266         1        29     348.0      2.0      5.00           0   
109267         1        21     252.0      3.0      5.00           1   
...          ...       ...       ...      ...       ...         ...   
124818         0        40     480.0      5.0      3.82           0   
124819         0         2      24.0      5.0      0.07           0   
124820         1         7      84.0      5.0      1.22           0   
124821         0        63     756.0      5.0      3.71           0   
124822         0        74     888.0      4.0       NaN           1   

        RIDRETH1_3  RIDRETH1_4  RIDRETH1_5  RIDRETH3_2  RIDRETH3_3  \
SEQN                                                                 
109263           0           0           1           0           0   
109264           0           0           0           0           0   
109265           1           0           0           0           1   
109266           0           0           1           0           0   
109267           0           0           0           1           0   
...            ...         ...         ...         ...         ...   
124818           0           1           0           0           0   
124819           0           1           0           0           0   
124820           1           0           0           0           1   
124821           0           1           0           0           0   
124822           0           0           0           1           0   

        RIDRETH3_4  RIDRETH3_6  RIDRETH3_7  DMDBORN4_2  DMDEDUC2_2.0  \
SEQN                                                                   
109263           0           1           0           0             0   
109264           0           0           0           0             0   
109265           0           0           0           0             0   
109266           0           1           0           1             0   
109267           0           0           0           1             0   
...            ...         ...         ...         ...           ...   
124818           1           0           0           0             0   
124819           1           0           0           0             0   
124820           0           0           0           0             0   
124821           1           0           0           0             1   
124822           0           0           0           1             0   

        DMDEDUC2_3.0  DMDEDUC2_4.0  DMDEDUC2_5.0  DMDEDUC2_6.0  DMDMARTZ_2.0  \
SEQN                                                                           
109263             0             0             0             1             0   
109264             0             0             0             1             0   
109265             0             0             0             1             0   
109266             0             0             1             0             0   
109267             0             1             0             0             0   
...              ...           ...           ...           ...           ...   
124818             0             0             1             0             0   
124819             0             0             0             1             0   
124820             0             0             0             1             0   
124821             0             0             0             0             1   
124822             1             0             0             0             0   

        DMDMARTZ_3.0  DMDMARTZ_4.0  RIDEXPRG_2.0  RIDEXPRG_3.0  RIDEXPRG_4.0  \
SEQN                                                                           
109263             0             1 

In [164]:
scaler = StandardScaler()
df_p_demo_subset_dummified_scaled = scaler.fit_transform(df_p_demo_subset_dummified)

df_p_demo_subset_dummified_scaled = pd.DataFrame(df_p_demo_subset_dummified_scaled, columns = cols_dummified, index = df_p_demo_subset_dummified.index)

In [165]:
df_p_demo_subset_dummified_scaled

RIAGENDR  RIDAGEYR  RIDAGEMN  DMDYRUSZ  INDFMPIR  RIDRETH1_2  \
SEQN                                                                   
109263 -1.007038 -1.247874 -1.250835  0.425272  1.375324   -0.328259   
109264  0.993011 -0.813886 -0.816210  0.425272 -0.968227   -0.328259   
109265 -1.007038 -1.247874 -1.250835  0.425272  0.396295   -0.328259   
109266  0.993011 -0.182631 -0.184029 -2.598363  1.583368   -0.328259   
109267  0.993011 -0.498259 -0.500119 -1.590485  1.583368    3.046371   
...          ...       ...       ...       ...       ...         ...   
124818 -1.007038  0.251357  0.250596  0.425272  0.861334   -0.328259   
124819 -1.007038 -1.247874 -1.250835  0.425272 -1.433266   -0.328259   
124820  0.993011 -1.050607 -1.053278  0.425272 -0.729588   -0.328259   
124821 -1.007038  1.158786  1.159357  0.425272  0.794026   -0.328259   
124822 -1.007038  1.592774  1.593982 -0.582606       NaN    3.046371   

        RIDRETH1_3  RIDRETH1_4  RIDRETH1_5  RIDRETH3_2  RIDRETH3_3  \
SEQN                                                                 
109263   -0.720754   -0.600754    2.202513   -0.328259   -0.720754   
109264   -0.720754   -0.600754   -0.454027   -0.328259   -0.720754   
109265    1.387435   -0.600754   -0.454027   -0.328259    1.387435   
109266   -0.720754   -0.600754    2.202513   -0.328259   -0.720754   
109267   -0.720754   -0.600754   -0.454027    3.046371   -0.720754   
...            ...         ...         ...         ...         ...   
124818   -0.720754    1.664576   -0.454027   -0.328259   -0.720754   
124819   -0.720754    1.664576   -0.454027   -0.328259   -0.720754   
124820    1.387435   -0.600754   -0.454027   -0.328259    1.387435   
124821   -0.720754    1.664576   -0.454027   -0.328259   -0.720754   
124822   -0.720754   -0.600754   -0.454027    3.046371   -0.720754   

        RIDRETH3_4  RIDRETH3_6  RIDRETH3_7  DMDBORN4_2  DMDEDUC2_2.0  \
SEQN                                                                   
109263   -0.600754    2.918548    -0.26549   -0.480128     -0.266051   
109264   -0.600754   -0.342636    -0.26549   -0.480128     -0.266051   
109265   -0.600754   -0.342636    -0.26549   -0.480128     -0.266051   
109266   -0.600754    2.918548    -0.26549    2.082776     -0.266051   
109267   -0.600754   -0.342636    -0.26549    2.082776     -0.266051   
...            ...         ...         ...         ...           ...   
124818    1.664576   -0.342636    -0.26549   -0.480128     -0.266051   
124819    1.664576   -0.342636    -0.26549   -0.480128     -0.266051   
124820   -0.600754   -0.342636    -0.26549   -0.480128     -0.266051   
124821    1.664576   -0.342636    -0.26549   -0.480128      3.758683   
124822   -0.600754   -0.342636    -0.26549    2.082776     -0.266051   

        DMDEDUC2_3.0  DMDEDUC2_4.0  DMDEDUC2_5.0  DMDEDUC2_6.0  DMDMARTZ_2.0  \
SEQN                                                                           
109263     -0.408573     -0.487385     -0.412999      1.200077     -0.399876   
109264     -0.408573     -0.487385     -0.412999      1.200077     -0.399876   
109265     -0.408573     -0.487385     -0.412999      1.200077     -0.399876   
109266     -0.408573     -0.487385      2.421311     -0.833280     -0.399876   
109267     -0.408573      2.051766     -0.412999     -0.833280     -0.399876   
...              ...           ...           ...           ...           ...   
124818     -0.408573     -0.487385      2.421311     -0.833280     -0.399876   
124819     -0.408573     -0.487385     -0.412999      1.200077     -0.399876   
124820     -0.408573     -0.487385     -0.412999      1.200077     -0.399876   
124821     -0.408573     -0.487385     -0.412999     -0.833280      2.500777   
124822      2.447543     -0.487385     -0.412999     -0.833280     -0.399876   

        DMDMARTZ_3.0  DMDMARTZ_4.0  RIDEXPRG_2.0  RIDEXPRG_3.0  RIDEXPRG_4.0  \
SEQN                                                                           
109263     -0.359902  

In [166]:
df_p_demo_imputed = pd.DataFrame(imputer.fit_transform(df_p_demo_subset_dummified_scaled), columns = cols_dummified, index = df_p_demo_subset_dummified_scaled.index)

df_p_demo_imputed = pd.DataFrame(scaler.inverse_transform(df_p_demo_imputed), columns = cols_dummified, index = df_p_demo_subset_dummified_scaled.index)

df_p_demo_imputed = df_p_demo_imputed.reset_index()

df_p_demo = df_p_demo.merge(df_p_demo_imputed[["SEQN", "INDFMPIR"]].rename(columns = {"INDFMPIR": "INDFMPIR_imputed"}), on = ["SEQN"] ,how = "left")

In [167]:
df_p_demo[df_p_demo["INDFMPIR"].isna()]

SEQN  SDDSRVYR  RIDSTATR  RIAGENDR  RIDAGEYR  RIDAGEMN  RIDRETH1  \
8      109271        66         2         0        49     588.0         3   
15     109278        66         2         1         6      72.0         2   
21     109284        66         2         1        44     528.0         1   
28     109291        66         2         1        42     504.0         5   
34     109297        66         2         1        30     360.0         5   
...       ...       ...       ...       ...       ...       ...       ...   
15378  124801        66         2         1         1      19.0         1   
15382  124805        66         2         1        66     792.0         4   
15385  124808        66         1         1        26     312.0         3   
15390  124813        66         2         1        43     516.0         4   
15399  124822        66         2         0        74     888.0         2   

       RIDRETH3 DMDBORN4 DMDYRUSZ  DMDEDUC2  DMDMARTZ  RIDEXPRG  SIALANG  \
8             3        1      5.0       2.0       3.0       4.0        1   
15            2        1      5.0       6.0       4.0       4.0        2   
21            1        2      3.0       2.0       1.0       2.0        2   
28            6        1      5.0       5.0       1.0       2.0        1   
34            6        1      5.0       4.0       3.0       2.0        1   
...         ...      ...      ...       ...       ...       ...      ...   
15378         1        1      5.0       6.0       4.0       4.0        2   
15382         4        2      4.0       3.0       1.0       4.0        1   
15385         3        1      5.0       3.0       1.0       3.0        1   
15390         4        2      1.0       5.0       1.0       2.0        1   
15399         2        2      4.0       3.0       1.0       4.0        2   

       SIAPROXY  SIAINTRP   WTINTPRP  WTMECPRP  SDMVPSU  SDMVSTRA  INDFMPIR  \
8             2         2    8481.59   8658.73        1       167       NaN   
15            1         2   10119.76  10958.71        1       171       NaN   
21            2         2   13822.80  13794.79        1       154       NaN   
28            2         2   15845.54  17228.62        1       161       NaN   
34            2         2   13785.40  14974.37        2       154       NaN   
...         ...       ...        ...       ...      ...       ...       ...   
15378         1         2    8739.99  10074.34        2       169       NaN   
15382         2         2   11442.16  11805.89        2       153       NaN   
15385         2         2  120856.82      0.00        2       149       NaN   
15390         2         2   10608.75  11901.46        2       171       NaN   
15399         2         2   14024.48  15195.80        1       149       NaN   

       INDFMPIR_imputed  
8                  0.00  
15                 0.44  
21                 1.50  
28                 5.00  
34                 2.79  
...                 ...  
15378              0.45  
15382              5.00  
15385              1.41  
15390              1.69  
15399              0.82  

[2127 rows x 22 columns]

The following features talk about weights and do not have any context to the dataset. We will proceed to remove them,
- WTINTPRP
- WTMECPRP
- SDMVPSU
- SDMVSTRA

In [168]:
df_p_demo = df_p_demo.drop(['WTINTPRP', 'WTMECPRP', 'SDMVPSU', 'SDMVSTRA'], axis = 1)

df_p_demo = df_p_demo.replace(np.nan, None)

In [169]:
df_p_demo

SEQN  SDDSRVYR  RIDSTATR  RIAGENDR  RIDAGEYR  RIDAGEMN  RIDRETH1  \
0      109263        66         2         0         2      24.0         5   
1      109264        66         2         1        13     156.0         1   
2      109265        66         2         0         2      24.0         3   
3      109266        66         2         1        29     348.0         5   
4      109267        66         1         1        21     252.0         2   
...       ...       ...       ...       ...       ...       ...       ...   
15395  124818        66         2         0        40     480.0         4   
15396  124819        66         2         0         2      24.0         4   
15397  124820        66         2         1         7      84.0         3   
15398  124821        66         2         0        63     756.0         4   
15399  124822        66         2         0        74     888.0         2   

       RIDRETH3 DMDBORN4 DMDYRUSZ  DMDEDUC2  DMDMARTZ  RIDEXPRG  SIALANG  \
0             6        1      5.0       6.0       4.0       4.0        1   
1             1        1      5.0       6.0       4.0       4.0        1   
2             3        1      5.0       6.0       4.0       4.0        1   
3             6        2      2.0       5.0       3.0       2.0        1   
4             2        2      3.0       4.0       3.0       3.0        1   
...         ...      ...      ...       ...       ...       ...      ...   
15395         4        1      5.0       5.0       1.0       4.0        1   
15396         4        1      5.0       6.0       4.0       4.0        1   
15397         3        1      5.0       6.0       4.0       4.0        1   
15398         4        1      5.0       2.0       2.0       4.0        1   
15399         2        2      4.0       3.0       1.0       4.0        2   

       SIAPROXY  SIAINTRP INDFMPIR  INDFMPIR_imputed  
0             1         2     4.66              4.66  
1             1         2     0.83              0.83  
2             1         2     3.06              3.06  
3             2         2      5.0              5.00  
4             2         2      5.0              5.00  
...         ...       ...      ...               ...  
15395         2         2     3.82              3.82  
15396         1         2     0.07              0.07  
15397         1         2     1.22              1.22  
15398         2         2     3.71              3.71  
15399         2         2     None              0.82  

[15400 rows x 18 columns]

In [170]:
my_conn = create_engine(f"mysql+mysqldb://{myvars['DB username']}:{myvars['DB password']}@localhost/{myvars['DB databasename']}") #fill details

In [171]:
cols = ['SEQN'
         ,'SDDSRVYR'
         ,'RIDSTATR'
         ,'RIAGENDR'
#          ,'RIDAGEYR' -- inconsistent data points ex: 5.39760535e-79
#          ,'RIDAGEMN' -- inconsistent data points ex: 5.39760535e-79
         ,'RIDRETH1'
         ,'RIDRETH3'
         ,'RIDEXMON'
         ,'DMDBORN4'
         ,'DMDYRUSZ'
         ,'DMDEDUC2'
         ,'DMDMARTZ'
         ,'RIDEXPRG'
         ,'SIALANG'
         ,'SIAPROXY'
         ,'SIAINTRP'
         ,'FIALANG'
         ,'FIAPROXY'
         ,'FIAINTRP'
         ,'MIALANG'
         ,'MIAPROXY'
         ,'MIAINTRP'
         ,'AIALANGA'
         ,'SDMVPSU'
         ,'SDMVSTRA']


for col in cols:
    if col in df_p_demo.columns:
        df_p_demo[col] = df_p_demo[col].astype("Int32")

In [172]:
cols = ['RIDAGEYR'
        ,'RIDAGEMN'
       ]

for col in cols:
    if col in df_p_demo.columns:
        df_p_demo[col] = df_p_demo[col].astype("Int32")

In [173]:
cols = ['WTINTPRP'
         ,'WTMECPRP'
         ,'INDFMPIR']

for col in cols:
    if col in df_p_demo.columns:
        df_p_demo[col] = df_p_demo[col].astype("float")

In [174]:
name = "P_DEMO_preprocess"
df_p_demo.to_sql(name, con = my_conn, if_exists = 'replace', index = False)

15400